---

  - name: Remove all in /var/www
    hosts: 127.0.0.1
    connection: local
    file: path=/var/www state=absent

  - name: Copy master /var/www to local /var/www
    fetch: src=/var/www dest=/var/www
