---

  - hosts: piwee_master
    tasks:

    - name: Dump DB on the master side
      shell: mysqldump --user=root --password={{ master_mysql_root_password }} -h {{ master_mysql_host }} piwee > /tmp/dump.sql

    - name: Copy remote dump to /tmp
      fetch: src=/tmp/dump.sql dest=/tmp flat=yes

  - hosts: piwee_slave
    tasks:

    - name: Remove current DB
      shell: mysql --user=root --password={{ slave_mysql_root_password }} -h {{ slave_mysql_host }} --execute="DROP DATABASE piwee"

    - name: Create new DB
      shell: mysql --user=root --password={{ slave_mysql_root_password }} -h {{ slave_mysql_host }} --execute="CREATE DATABASE piwee"

    - name: Restore dump file from master
      shell: mysql --user=root --password={{ slave_mysql_root_password }} -h {{ slave_mysql_host }} piwee < /tmp/dump.sql
