---

  - hosts: piwee_slave
    tasks:

    - name: Remove all in /var/www
      file: path=/var/www state=absent

  - hosts: piwee_master
    tasks:

    - name: Copy master /var/www to local /var/www
      synchronize: src=/var/www dest=/var
