---

  - hosts: piwee_slave
    tasks:

    - name: Remove all in /var/www
      file: path=/var/www state=absent

  - hosts: piwee_master
    tasks:

    - name: Zip /var/www on master
      shell: tar -zcvf /tmp/www.tar.gz /var/www/*

    - name: Fetch master www.tar.gz previously created to local /tmp
      fetch: src=/tmp/www.tar.gz dest=/tmp flat=yes

  - hosts: piwee_slave
    tasks:

    - name: Ensure /var/www does exists
      file: path=/var/www state=directory mode=0755 owner=www-data group=www-data

    - name: Unarchive www.tar.gz
      unarchive: src=/tmp/www.tar.gz dest=/tmp

    - name: Ensure /var/www is owned by the correct group / has the correct chmod
      file: path=/var/www state=directory mode=0755 owner=www-data group=www-data recurse=yes

    - name: Copy /tmp/var/www/* to /var/www
      shell: cp -R /tmp/var/www/* /var/www

    - name: Clean tmp folder from var/
      file: path=/tmp/var state=absent

    - name: Clean tmp folder from www.tar.gz
      file: path=/tmp/www.tar.gz state=absent
