---

  - hosts: 127.0.0.1
    tasks:

    - name: Remove all in /var/www
      file: path=/var/www state=absent

  - hosts: all
    tasks:

    - name: Copy master /var/www to local /var/www
      fetch: src=/var/www dest=/var/www
